/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import resto.dao.Conexion;
import resto.dao.ProductoData;
import resto.entidades.Producto;

/**
 *
 * @author Valeria
 */
public class ActualizarProductoVista extends javax.swing.JPanel {
    private Conexion con;
    private ProductoData pd;
    private int codigo;
    
    public ActualizarProductoVista(int codigo) {
        initComponents();
        con = new Conexion();
        pd = new ProductoData(con);
        this.codigo = codigo;
        llenarCampos(codigo);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jbVolver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jsStock = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jchActivo = new javax.swing.JCheckBox();
        jpFondoAgregar2 = new javax.swing.JPanel();
        jbAgregar2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 239, 239));
        setPreferredSize(new java.awt.Dimension(780, 530));

        escritorio.setBackground(new java.awt.Color(240, 239, 239));
        escritorio.setPreferredSize(new java.awt.Dimension(780, 530));

        jbVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/img/iconoAtras.png"))); // NOI18N
        jbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbVolverMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 63, 50));
        jLabel1.setText("Actualizar Producto");

        jSeparator1.setBackground(new java.awt.Color(114, 63, 50));
        jSeparator1.setForeground(new java.awt.Color(114, 63, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNombreFocusLost(evt);
            }
        });
        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel4.setText("Precio");

        jtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPrecioFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel5.setText("Categoría");

        jcbCategoria.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comidas", "Bebidas" }));
        jcbCategoria.setSelectedIndex(-1);
        jcbCategoria.setToolTipText("");
        jcbCategoria.setBorder(null);
        jcbCategoria.setName(""); // NOI18N
        jcbCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbCategoriaFocusLost(evt);
            }
        });
        jcbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel3.setText("Stock");

        jsStock.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel6.setText("Activo");

        jchActivo.setPreferredSize(new java.awt.Dimension(30, 30));
        jchActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchActivoActionPerformed(evt);
            }
        });

        jpFondoAgregar2.setBackground(new java.awt.Color(241, 207, 178));

        jbAgregar2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jbAgregar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbAgregar2.setText("Actualizar");
        jbAgregar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAgregar2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAgregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAgregar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbAgregar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbAgregar2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpFondoAgregar2Layout = new javax.swing.GroupLayout(jpFondoAgregar2);
        jpFondoAgregar2.setLayout(jpFondoAgregar2Layout);
        jpFondoAgregar2Layout.setHorizontalGroup(
            jpFondoAgregar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAgregar2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jpFondoAgregar2Layout.setVerticalGroup(
            jpFondoAgregar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbAgregar2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 50, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(escritorioLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jsStock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jchActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jcbCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jbVolver))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jpFondoAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jbVolver)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jsStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jchActivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jpFondoAgregar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    private void jbAgregar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregar2MouseEntered
        jpFondoAgregar2.setBackground(Color.decode("#D9B18E"));
    }//GEN-LAST:event_jbAgregar2MouseEntered

    private void jbAgregar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregar2MouseExited
        jpFondoAgregar2.setBackground(Color.decode("#F1CFB2"));
    }//GEN-LAST:event_jbAgregar2MouseExited

    private void jbVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbVolverMouseClicked
        ProductoVista prv = new ProductoVista(con);
        
        prv.setSize(780, 530);
        prv.setLocation(0, 0);

        escritorio.removeAll();
        escritorio.add(prv);
        escritorio.revalidate();
        escritorio.repaint();
    }//GEN-LAST:event_jbVolverMouseClicked

    private void jcbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbCategoriaActionPerformed

    private void jchActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jchActivoActionPerformed

    private void jtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNombreFocusLost

    }//GEN-LAST:event_jtNombreFocusLost

    private void jtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPrecioFocusLost
      
        
    }//GEN-LAST:event_jtPrecioFocusLost

    private void jbAgregar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregar2MouseClicked

        String comest = "";
        int com;
        boolean insertar = true;
   
        if(jcbCategoria.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Debe elegir una categoria para el producto.");
            jcbCategoria.requestFocus();
            insertar = false;   
        }
  
        try{
            String pre = jtPrecio.getText();
            double precio = Double.parseDouble(pre);
        }catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Debe ingresar un precio válido para el producto.");
           jtPrecio.requestFocus();
           insertar = false;
        }
        
        if(jtNombre.getText().length()==0){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre para el producto.");
            jtNombre.requestFocus();
            insertar = false;
        }
        
        if(jtNombre.getText().length()>60){
            JOptionPane.showMessageDialog(this, "El nombre del producto es demasiado largo.");
            jtNombre.requestFocus();
            insertar = false;
        }

        
        if(insertar){
            Producto p = new Producto();
            
            p.setCodigo(this.codigo);
            p.setNombre(jtNombre.getText());
            p.setPrecio(Double.parseDouble(jtPrecio.getText()));

            com = jcbCategoria.getSelectedIndex();
            if(com == -1){
                JOptionPane.showMessageDialog(this, "Debe seleccionar una categoria para el producto.");
            }

            comest = jcbCategoria.getSelectedItem().toString();    
            if(comest.equals("Comidas")){
                p.setComestible(true);
            }else{
                p.setComestible(false);
            }

            p.setStock((Integer)jsStock.getValue());
            p.setActivo(jchActivo.isSelected());
            
            pd.modificarProducto(p);
        
            
            JOptionPane.showMessageDialog(this, "Producto modificado exitosamente.");
        }     
    }//GEN-LAST:event_jbAgregar2MouseClicked

    private void jcbCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbCategoriaFocusLost
        
    }//GEN-LAST:event_jcbCategoriaFocusLost

    private void limpiarCampos(){
        jtNombre.setText("");
        jtPrecio.setText("");
        jcbCategoria.setSelectedIndex(-1);
        jsStock.setValue(0);
        jchActivo.setSelected(false);
    }
    
    private void llenarCampos(int codigo){
        Producto p = new Producto();
        p = pd.obtenerProducto(codigo);
        
        jtNombre.setText(p.getNombre());
        jtPrecio.setText(p.getPrecio() + "");
        jcbCategoria.setSelectedIndex(p.isComestible()? 0 : 1);
        jsStock.setValue(p.getStock());
        jchActivo.setSelected(p.isActivo());   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbAgregar2;
    private javax.swing.JLabel jbVolver;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JCheckBox jchActivo;
    private javax.swing.JPanel jpFondoAgregar2;
    private javax.swing.JSpinner jsStock;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPrecio;
    // End of variables declaration//GEN-END:variables
}
