/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resto.vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import resto.dao.Conexion;
import resto.dao.MesaData;
import resto.entidades.Mesa;
import resto.entidades.Mesero;

/**
 *
 * @author edder
 */
public class CrearMesasVista extends javax.swing.JPanel {

    private MesaData mesadata;

    /**
     * Creates new form VistaCrearMesas
     */
    public CrearMesasVista(Conexion coneccion) {
        initComponents();
        mesadata = new MesaData(coneccion);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cMcapacidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mVfondoAgregar = new javax.swing.JPanel();
        cMbtnAgregar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cMnumMesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mVfondoNuevaMesa = new javax.swing.JPanel();
        cMbtnNuevo = new javax.swing.JLabel();
        cMVatras = new javax.swing.JPanel();
        cMVbtnVolver = new javax.swing.JLabel();
        cMestado = new resto.componentes.CheckboxPersonalizada();
        cMactiva = new resto.componentes.CheckboxPersonalizada();

        setBackground(new java.awt.Color(240, 239, 239));
        setPreferredSize(new java.awt.Dimension(780, 530));

        escritorio.setBackground(new java.awt.Color(240, 239, 239));

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(114, 63, 50));
        jLabel1.setText("Agregar mesa nueva");

        cMcapacidad.setBackground(new java.awt.Color(240, 239, 239));
        cMcapacidad.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setText("Capacidad");

        mVfondoAgregar.setBackground(new java.awt.Color(241, 207, 178));
        mVfondoAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cMbtnAgregar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        cMbtnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cMbtnAgregar.setText("Agregar");
        cMbtnAgregar.setAlignmentY(0.0F);
        cMbtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cMbtnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMbtnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cMbtnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cMbtnAgregarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mVfondoAgregarLayout = new javax.swing.GroupLayout(mVfondoAgregar);
        mVfondoAgregar.setLayout(mVfondoAgregarLayout);
        mVfondoAgregarLayout.setHorizontalGroup(
            mVfondoAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cMbtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mVfondoAgregarLayout.setVerticalGroup(
            mVfondoAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cMbtnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(241, 207, 178));
        jPanel3.setToolTipText("");

        jLabel4.setBackground(new java.awt.Color(241, 207, 178));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/img/mesaImg.png"))); // NOI18N

        cMnumMesa.setEditable(false);
        cMnumMesa.setBackground(new java.awt.Color(241, 207, 178));
        cMnumMesa.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        cMnumMesa.setBorder(null);
        cMnumMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMnumMesaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setText("Mesa N°");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cMnumMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cMnumMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/img/iconoSillaMesa.png"))); // NOI18N

        mVfondoNuevaMesa.setBackground(new java.awt.Color(241, 207, 178));
        mVfondoNuevaMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cMbtnNuevo.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        cMbtnNuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cMbtnNuevo.setText("Nueva Mesa");
        cMbtnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cMbtnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cMbtnNuevoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cMbtnNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cMbtnNuevoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mVfondoNuevaMesaLayout = new javax.swing.GroupLayout(mVfondoNuevaMesa);
        mVfondoNuevaMesa.setLayout(mVfondoNuevaMesaLayout);
        mVfondoNuevaMesaLayout.setHorizontalGroup(
            mVfondoNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cMbtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mVfondoNuevaMesaLayout.setVerticalGroup(
            mVfondoNuevaMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cMbtnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        cMVatras.setBackground(new java.awt.Color(241, 207, 178));
        cMVatras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cMVbtnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cMVbtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resto/img/iconoAtras.png"))); // NOI18N
        cMVbtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cMVbtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cMVbtnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cMVbtnVolverMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cMVbtnVolverMousePressed(evt);
            }
        });

        javax.swing.GroupLayout cMVatrasLayout = new javax.swing.GroupLayout(cMVatras);
        cMVatras.setLayout(cMVatrasLayout);
        cMVatrasLayout.setHorizontalGroup(
            cMVatrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cMVbtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );
        cMVatrasLayout.setVerticalGroup(
            cMVatrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cMVbtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        cMestado.setText("Ocupada");
        cMestado.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        cMestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMestadoActionPerformed(evt);
            }
        });

        cMactiva.setSelected(true);
        cMactiva.setText("Activa");
        cMactiva.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cMVatras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mVfondoAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cMcapacidad)
                            .addComponent(mVfondoNuevaMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cMestado, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(cMactiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(251, 251, 251)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cMVatras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(cMcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cMestado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cMactiva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mVfondoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(mVfondoNuevaMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    private void cMbtnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMbtnAgregarMouseEntered
        // TODO add your handling code here:
        mVfondoAgregar.setBackground(Color.decode("#D9B18E"));
    }//GEN-LAST:event_cMbtnAgregarMouseEntered

    private void cMbtnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMbtnAgregarMouseExited
        // TODO add your handling code here:
        mVfondoAgregar.setBackground(Color.decode("#F1CFB2"));
    }//GEN-LAST:event_cMbtnAgregarMouseExited

    private void cMbtnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMbtnAgregarMouseClicked
        // TODO add your handling code here:
        try {
            //Capturar datos del formulario
            int capacidad = Integer.parseInt(cMcapacidad.getText());
            boolean estado = cMestado.isSelected();
            boolean activo = cMactiva.isSelected();
            //crear una mesa
            Mesa mesa = new Mesa(capacidad, estado, activo);
            //enviar a la BD la mesa
            if (mesadata.crearMesaVista(mesa)) {
                cMnumMesa.setText(mesa.getNumMesa() + "");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese la Capacidad de la Nueva Mesa. " +ex);
        }

    }//GEN-LAST:event_cMbtnAgregarMouseClicked

    private void cMnumMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMnumMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMnumMesaActionPerformed

    private void cMbtnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMbtnNuevoMouseEntered
        // TODO add your handling code here:
        mVfondoNuevaMesa.setBackground(new Color(217, 177, 142));
    }//GEN-LAST:event_cMbtnNuevoMouseEntered

    private void cMbtnNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMbtnNuevoMouseExited
        // TODO add your handling code here:
        mVfondoNuevaMesa.setBackground(new Color(241, 207, 178));
    }//GEN-LAST:event_cMbtnNuevoMouseExited

    private void cMbtnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMbtnNuevoMouseClicked
        // TODO add your handling code here:
        cMnumMesa.setText("");
        cMcapacidad.setText("");
        cMestado.setSelected(false);
        cMactiva.setSelected(true);
    }//GEN-LAST:event_cMbtnNuevoMouseClicked

    private void cMVbtnVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMVbtnVolverMousePressed
        // TODO add your handling code here:
        Conexion coneccion = new Conexion();
        MesaVista mv = new MesaVista(coneccion);
        mv.setSize(780, 530);
        mv.setLocation(0, 0);

        escritorio.removeAll();
        escritorio.add(mv, BorderLayout.CENTER);
        escritorio.revalidate();
        escritorio.repaint();
    }//GEN-LAST:event_cMVbtnVolverMousePressed

    private void cMVbtnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMVbtnVolverMouseEntered
        // TODO add your handling code here:
        cMVatras.setBackground(new Color(217, 177, 142));
    }//GEN-LAST:event_cMVbtnVolverMouseEntered

    private void cMVbtnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMVbtnVolverMouseExited
        // TODO add your handling code here:
        cMVatras.setBackground(new Color(241, 207, 178));
    }//GEN-LAST:event_cMVbtnVolverMouseExited

    private void cMestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMestadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cMVatras;
    private javax.swing.JLabel cMVbtnVolver;
    private resto.componentes.CheckboxPersonalizada cMactiva;
    private javax.swing.JLabel cMbtnAgregar;
    private javax.swing.JLabel cMbtnNuevo;
    private javax.swing.JTextField cMcapacidad;
    private resto.componentes.CheckboxPersonalizada cMestado;
    private javax.swing.JTextField cMnumMesa;
    private javax.swing.JPanel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mVfondoAgregar;
    private javax.swing.JPanel mVfondoNuevaMesa;
    // End of variables declaration//GEN-END:variables
}
